os:
- linux
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
before_install:
- pip install --user codecov
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_swiftlint.sh; fi
- curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
- . ~/.swiftenv/init
- rm -rf Packages .build
- swift build --fetch
- rm -rf Packages/*/Tests
- swift build
- swift test
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then swiftlint; fi
after_success:
- codecov
